dataset_type: "mnist"
train_image_path_txt: "tmp/face10000.txt"
emnist_data_path: "tmp/emnist_gzip/emnist-letters-train-images-idx3-ubyte.gz"
max_iter: 500000
batch_size: 128
snapshot_iter_interval: 10000
display_iter_interval: 10000
n_discriminator_update: 1
evaluation_iter_interval: 10000
alpha: 0.001
beta1: 0.5
beta2: 0.999
discriminator_ch_size: 128
