# train_image_dir_path: "test/dammy_image_data"
train_image_path_txt: "tmp/face10000.txt"
max_iter: 1000000
batch_size: 128
snapshot_iter_interval: 10000
display_iter_interval: 500
evaluation_iter_interval: 5000
alpha: 0.01
beta1: 0.5
beta2: 0.999
