# train_image_dir_path: "test/dammy_image_data"
train_image_path_txt: "tmp/face10000.txt"
max_iter: 1000000
batch_size: 64
snapshot_iter_interval: 10000
display_iter_interval: 100
n_discriminator_update: 1
evaluation_iter_interval: 10000
alpha: 0.0002
beta1: 0.5
beta2: 0.999
discriminator_ch_size: 36
