# train_image_dir_path: "test/dammy_image_data"
train_image_path_txt: "tmp/face10000.txt"
max_iter: 1000000
batch_size: 64
snapshot_iter_interval: 5000
display_iter_interval: 100
n_discriminator_update: 1
evaluation_iter_interval: 5000
alpha: 0.0001
beta1: 0.05
